# Generated by Django 5.1.4 on 2025-01-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='raised_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
